### PR TITLE
fixed pyomo release compatibility issues

### PR DESCRIPTION
**Pull request by ddceruti**
So I tried to install romodel and noticed pyomo version compatibility issues:
1) pyomo==6.0 does not require pytulib -> added to requirements and setup.py
2) pyomo==5.7.3. does not support ScalarBlock -> latest commit does not work
3) pyomo 6.4.2 throws an error  in romodel/uncparam.py constructor 
`AttributeError: 'IndexedUncParam' object has no attribute '_index'`

Therefore I updated setup.py and requirements with pyomo == 6.0 and pyutilib. Works on windows 10 and python 3.10 w_th gurobi. 

Additionally updated the version to the latest romodel release v0.1.0

### CODE REVIEW

**Comment by ddceruti** [comment]
Additional info on the ScalarBlock commit:  #1  which causes #2 due to pyomo >= 6.0 defaulting to latest 6.4.2 release.

**Comment by rmisener** [comment]
Thanks a lot for this. I'm going to contact Johannes and see if he has time to review this.
